In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/Himanshu-1703/reddit-sentiment-analysis/refs/heads/main/data/reddit.csv")

In [ ]:
df.head()

                                       clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

In [ ]:
df.shape

(37249, 2)

In [ ]:
df['category'].value_counts()

category
 1    15830
 0    13142
-1     8277
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

clean_comment    100
category           0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

clean_comment    0
category         0
dtype: int64

In [ ]:
df.shape

(37149, 2)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(36799, 2)

In [ ]:
df[(df['clean_comment'].str.strip() == '')]

                clean_comment  category
181                                   0
4432                       \n         0
10592                                 0
16173                                 0
32149  \n                             0
34959                                 0

In [ ]:
df = df[~(df['clean_comment'].str.strip() == '')]

In [ ]:
df['clean_comment'] = df['clean_comment'].str.lower()

In [ ]:
df[df['clean_comment'].apply(lambda x: x.endswith(' ') or x.startswith(' '))]

                                           clean_comment  category
0       family mormon have never tried explain them t...         1
1      buddhism has very much lot compatible with chr...         1
2      seriously don say thing first all they won get...        -1
3      what you have learned yours and only yours wha...         0
4      for your own benefit you may want read living ...         1
...                                                  ...       ...
37241            let the janta decide not ulema clerics          0
37242   hona hai same with vaccination education insu...         0
37246              downvote karna tha par upvote hogaya          0
37247                                         haha nice          1
37248             facebook itself now working bjp’ cell          0

[32266 rows x 2 columns]

In [ ]:
df['clean_comment'].apply(lambda x: x.endswith(' ') or x.startswith(' ')).sum()

np.int64(32266)

In [ ]:
df['clean_comment'] = df['clean_comment'].str.strip()
df['clean_comment'].apply(lambda x: x.endswith(' ') or x.startswith(' ')).sum()

np.int64(0)

In [ ]:
# Removing URLs from comments
url_pattern = r"^(https?):\/\/([a-zA-Z0-9.-]+)(:[0-9]+)?(\/[^\s]*)?$"

comments_with_urls = df[df['clean_comment'].str.contains(url_pattern, regex=True)]

comments_with_urls.head()

/tmp/ipykernel_2429/266627839.py:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  comments_with_urls = df[df['clean_comment'].str.contains(url_pattern, regex=True)]

Empty DataFrame
Columns: [clean_comment, category]
Index: []

In [ ]:
# is there any new lines in comments
newlines_in_comments = df[df['clean_comment'].str.contains('\n')]
newlines_in_comments.head()

                                          clean_comment  category
448   what missing jpg\nand why this brilliant edit ...         1
781   india has been ruined congress and populist sc...        -1
847   like aap for its stand corruption and making p...        -1
871   reduced trade\ndeficit stronger rupee aren the...         0
1354  amsa press conference australian maritime safe...         1

In [ ]:
# Removing newline (\n) from comments
df['clean_comment'] = df['clean_comment'].str.replace('\n', ' ', regex=True)

In [ ]:
# is there any new lines in comments
newlines_in_comments = df[df['clean_comment'].str.contains('\n')]
newlines_in_comments.head()

Empty DataFrame
Columns: [clean_comment, category]
Index: []

In [ ]:
df.shape

(36793, 2)

In [ ]:
df.to_csv("preprocessed_df.csv")