In [5]:
pip install scikit-learn xgboost nltk pandas numpy dvc PyYAML

Requirement already satisfied: scikit-learn in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.9.0)
Requirement already satisfied: xgboost in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.4.0)
Requirement already satisfied: nltk in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.10.1)
Requirement already satisfied: pandas in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.5.1)
Requirement already satisfied: dvc in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.67.1)
Requirement already satisfied: PyYAML in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (6.0.3)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: defusedxml in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (8.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (2026.7.19)
Requirement already satisfied: tqdm in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (4.70.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\as296\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: attrs>=22.2.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (26.1.0)
Requirement already satisfied: celery in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (5.6.3)
Requirement already satisfied: colorama>=0.3.9 in C:\Users\as296\AppData\Roaming\Python\Python313\site-packages (from dvc) (0.4.6)
Requirement already satisfied: configobj>=5.0.9 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (5.0.9)
Requirement already satisfied: distro>=1.3 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.9.0)
Requirement already satisfied: dpath<3,>=2.1.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2.2.0)
Requirement already satisfied: dulwich in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.2.12)
Requirement already satisfied: dvc-data<3.19.0,>=3.18.2 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (3.18.3)
Requirement already satisfied: dvc-http>=2.29.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2.32.0)
Requirement already satisfied: dvc-objects in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (5.2.0)
Requirement already satisfied: dvc-render<2,>=1.0.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.0.2)
Requirement already satisfied: dvc-studio-client<1,>=0.21 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.23.0)
Requirement already satisfied: dvc-task<1,>=0.3.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.40.2)
Requirement already satisfied: flatten-dict<1,>=0.4.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.5.0)
Requirement already satisfied: flufl.lock<10,>=8.1.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (9.1.0)
Requirement already satisfied: fsspec>=2024.2.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2026.7.0)
Requirement already satisfied: funcy>=1.14 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2.0)
Requirement already satisfied: grandalf<1,>=0.7 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.8)
Requirement already satisfied: gto<2,>=1.6.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.10.1)
Requirement already satisfied: hydra-core>=1.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.3.4)
Requirement already satisfied: iterative-telemetry>=0.0.7 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.0.10)
Requirement already satisfied: kombu in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (5.6.2)
Requirement already satisfied: networkx>=2.5 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (3.6.1)
Requirement already satisfied: omegaconf in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2.3.1)
Requirement already satisfied: packaging>=19 in C:\Users\as296\AppData\Roaming\Python\Python313\site-packages (from dvc) (26.2)
Requirement already satisfied: pathspec<2,>=0.10.3 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.1.1)
Requirement already satisfied: platformdirs<5,>=3.1.1 in C:\Users\as296\AppData\Roaming\Python\Python313\site-packages (from dvc) (4.11.0)
Requirement already satisfied: psutil>=5.8 in C:\Users\as296\AppData\Roaming\Python\Python313\site-packages (from dvc) (7.2.2)
Requirement already satisfied: pydot>=1.2.4 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (4.0.1)
Requirement already satisfied: pygtrie>=2.3.2 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2.5.0)
Requirement already satisfied: pyparsing>=3.0.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (3.3.2)
Requirement already satisfied: requests>=2.22 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (2.34.2)
Requirement already satisfied: rich>=12 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (15.0.0)
Requirement already satisfied: ruamel.yaml>=0.17.11 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.19.1)
Requirement already satisfied: scmrepo<4,>=3.5.2 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (3.6.2)
Requirement already satisfied: shortuuid>=0.5 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.0.13)
Requirement already satisfied: shtab<2,>=1.3.4 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (1.9.3)
Requirement already satisfied: tabulate>=0.8.7 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.10.0)
Requirement already satisfied: tomlkit>=0.11.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.15.1)
Requirement already satisfied: voluptuous>=0.11.7 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (0.16.0)
Requirement already satisfied: zc.lockfile>=1.2.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc) (4.0)
Requirement already satisfied: dictdiffer>=0.8.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (0.10.0)
Requirement already satisfied: diskcache>=5.2.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (5.6.3)
Requirement already satisfied: sqltrie<1,>=0.11.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (0.11.2)
Requirement already satisfied: orjson<4,>=3 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (3.11.9)
Requirement already satisfied: pywin32>=225 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dvc-task<1,>=0.3.0->dvc) (312)
Requirement already satisfied: billiard<5.0,>=4.2.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (4.2.4)
Requirement already satisfied: vine<6.0,>=5.1.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (5.1.0)
Requirement already satisfied: click-didyoumean>=0.3.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (0.3.1)
Requirement already satisfied: click-repl>=0.2.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (0.3.0)
Requirement already satisfied: click-plugins>=1.1.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (1.1.1.2)
Requirement already satisfied: tzlocal in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from celery->dvc) (5.4.4)
Requirement already satisfied: atpublic in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from flufl.lock<10,>=8.1.0->dvc) (7.0.0)
Requirement already satisfied: entrypoints in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gto<2,>=1.6.0->dvc) (0.4)
Requirement already satisfied: pydantic>=2 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gto<2,>=1.6.0->dvc) (2.13.4)
Requirement already satisfied: pydantic-settings>=2 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gto<2,>=1.6.0->dvc) (2.14.2)
Requirement already satisfied: semver>=2.13.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gto<2,>=1.6.0->dvc) (3.0.4)
Requirement already satisfied: amqp<6.0.0,>=5.1.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kombu->dvc) (5.3.1)
Requirement already satisfied: gitpython>3 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scmrepo<4,>=3.5.2->dvc) (3.1.58)
Requirement already satisfied: pygit2>=1.14.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scmrepo<4,>=3.5.2->dvc) (1.19.3)
Requirement already satisfied: asyncssh<3,>=2.13.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scmrepo<4,>=3.5.2->dvc) (2.24.0)
Requirement already satisfied: aiohttp-retry>=2.5.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scmrepo<4,>=3.5.2->dvc) (2.9.1)
Requirement already satisfied: cryptography>=48.0.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (50.0.0)
Requirement already satisfied: typing_extensions>=4.0.0 in C:\Users\as296\AppData\Roaming\Python\Python313\site-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (4.16.0)
Requirement already satisfied: urllib3>=2.2.2 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from dulwich->dvc) (2.7.0)
Requirement already satisfied: aiohttp in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (3.14.3)
Requirement already satisfied: prompt-toolkit>=3.0.36 in C:\Users\as296\AppData\Roaming\Python\Python313\site-packages (from click-repl>=0.2.0->celery->dvc) (3.0.53)
Requirement already satisfied: cffi>=2.0.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from cryptography>=48.0.1->asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (2.1.1)
Requirement already satisfied: pycparser in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from cffi>=2.0.0->cryptography>=48.0.1->asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (3.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gitpython>3->scmrepo<4,>=3.5.2->dvc) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython>3->scmrepo<4,>=3.5.2->dvc) (5.0.3)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from hydra-core>=1.1->dvc) (4.9.3)
Requirement already satisfied: appdirs in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from iterative-telemetry>=0.0.7->dvc) (1.4.4)
Requirement already satisfied: filelock in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from iterative-telemetry>=0.0.7->dvc) (3.32.2)
Requirement already satisfied: wcwidth>=0.1.4 in C:\Users\as296\AppData\Roaming\Python\Python313\site-packages (from prompt-toolkit>=3.0.36->click-repl>=0.2.0->celery->dvc) (0.8.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic-settings>=2->gto<2,>=1.6.0->dvc) (1.2.2)
Requirement already satisfied: six>=1.5 in C:\Users\as296\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.22->dvc) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.22->dvc) (3.18)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.22->dvc) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich>=12->dvc) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\as296\AppData\Roaming\Python\Python313\site-packages (from rich>=12->dvc) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12->dvc) (0.1.2)
Requirement already satisfied: setuptools in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from zc.lockfile>=1.2.1->dvc) (83.0.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\Users\as296\AppData\Local\Programs\Python\Python313\Lib\site-packages (from aiohttp->aiohttp-retry>=2.5.0->scmrepo<4,>=3.5.2->dvc) (1.24.5)

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import re 
import nltk
import string
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer, WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/entbappy/Branching-tutorial/refs/heads/master/tweet_emotions.csv")

In [4]:
df.head()

     tweet_id   sentiment                                            content
0  1956967341       empty  @tiffanylue i know  i was listenin to bad habi...
1  1956967666     sadness  Layin n bed with a headache  ughhhh...waitin o...
2  1956967696     sadness                Funeral ceremony...gloomy friday...
3  1956967789  enthusiasm               wants to hang out with friends SOON!
4  1956968416     neutral  @dannycastillo We want to trade with someone w...

In [5]:
df.drop(columns=['tweet_id'], inplace=True)

In [6]:
df.head()

    sentiment                                            content
0       empty  @tiffanylue i know  i was listenin to bad habi...
1     sadness  Layin n bed with a headache  ughhhh...waitin o...
2     sadness                Funeral ceremony...gloomy friday...
3  enthusiasm               wants to hang out with friends SOON!
4     neutral  @dannycastillo We want to trade with someone w...

In [7]:
df['sentiment'].unique()

<StringArray>
[     'empty',    'sadness', 'enthusiasm',    'neutral',      'worry',
   'surprise',       'love',        'fun',       'hate',  'happiness',
    'boredom',     'relief',      'anger']
Length: 13, dtype: str

In [8]:
df = df[df["sentiment"].isin(["sadness","happiness"])]

In [20]:
shuffled_df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [21]:
shuffled_df.head()

   sentiment                                            content
0    sadness   looks like we're rained out for weekend climbing
1    sadness  Hi Everyone miss me much?  muahhhhhhhhhhhhhhhh...
2    sadness  rode the moped to the mall. fun stuff, its fli...
3    sadness  gutted!!! vodafone wont repair my faulty Samsu...
4  happiness             @shadowowns aww, &lt;3 why thank youu.

In [22]:
shuffled_df.shape

(10374, 2)

In [40]:
df_content = pd.DataFrame()

In [45]:
df_content['content'] = shuffled_df['content'].values

In [47]:
type(df_content)

pandas.DataFrame

In [32]:
df_sentiment = pd.DataFrame()

In [33]:
df_sentiment['sentiment'] = shuffled_df['sentiment'].map({"happiness":1, "sadness":0})

In [35]:
df_sentiment

       sentiment
0              0
1              0
2              0
3              0
4              1
...          ...
10369          1
10370          0
10371          1
10372          0
10373          0

[10374 rows x 1 columns]

In [ ]:
final_df = pd.concat([df_content, df_sentiment], axis=1)

In [51]:
final_df.head()

                                             content  sentiment
0   looks like we're rained out for weekend climbing          0
1  Hi Everyone miss me much?  muahhhhhhhhhhhhhhhh...          0
2  rode the moped to the mall. fun stuff, its fli...          0
3  gutted!!! vodafone wont repair my faulty Samsu...          0
4             @shadowowns aww, &lt;3 why thank youu.          1

In [52]:
train_data, test_data = train_test_split(final_df, test_size=.2, random_state=42)

# Data Preprocessing

In [53]:
nltk.download("wordnet")
nltk.download("stopwords")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\as296\AppData\Roaming\nltk_data...
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\as296\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [62]:
def lemmatization(text):
    lemmatizer = WordNetLemmatizer()

    text = text.split()

    text = [lemmatizer.lemmatize(y) for y in text]

    return " ".join(text)

In [69]:
def remove_stopwords(text):
    stop_words = set(stopwords.words("english"))
    text = [i for i in str(text).split() if i not in stop_words]

    return " ".join(text)

In [72]:
final_df['content'][2]

"rode the moped to the mall. fun stuff, its flippin gorgeous out. I'm sad that @maeannette is sick"

In [71]:
remove_stopwords(final_df['content'][2])

"rode moped mall. fun stuff, flippin gorgeous out. I'm sad @maeannette sick"

In [75]:
def remove_num(text):
    text = [i for i in text if not i.isdigit()]
    return "".join(text)

In [76]:
remove_num("hi, I am Asif 021")

'hi, I am Asif '

In [77]:
def lower_case(text):
    text = text.split()
    text = [y.lower() for y in text]

    return " ".join(text)

In [78]:
lower_case("hi I am ASIF")

'hi i am asif'

In [112]:
def remove_punctuatons(text):
    text = re.sub('[%s]' % re.escape("""`~!@#$%^&*()_-?+=.[\]{|}><,/:"""), ' ', text)
    text = text.replace(":","",)
    text = re.sub("\s+",' ', text)
    text = " ".join(text.split())

    return text.strip()

<>:2: SyntaxWarning: invalid escape sequence '\]'
<>:4: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\]'
<>:4: SyntaxWarning: invalid escape sequence '\s'
C:\Users\as296\AppData\Local\Temp\ipykernel_1436\2147044742.py:2: SyntaxWarning: invalid escape sequence '\]'
  text = re.sub('[%s]' % re.escape("""`~!@#$%^&*()_-?+=.[\]{|}><,/:"""), ' ', text)
C:\Users\as296\AppData\Local\Temp\ipykernel_1436\2147044742.py:4: SyntaxWarning: invalid escape sequence '\s'
  text = re.sub("\s+",' ', text)

In [85]:
remove_punctuatons("hi, asif.@ #$%^&/*()-_=/+")

'hi asif'

In [86]:
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

In [87]:
remove_urls("this is a song https://www.youtube.com/watch?v=-63rM58hDAU&list=RD-63rM58hDAU&start_radio=1")

'this is a song '

In [105]:
def remove_small_sentences(df):
    for i in range(len(df)):
        if len(df.content.iloc[i].split()) <3:
            df.content.iloc[i] = np.nan

In [107]:
def normalize_text(df):
    df.content = df.content.apply(lambda content: lemmatization(content))
    df.content = df.content.apply(lambda content: remove_num(content))
    df.content = df.content.apply(lambda content: remove_punctuatons(content))
    df.content = df.content.apply(lambda content: remove_stopwords(content))
    df.content = df.content.apply(lambda content: remove_urls(content))
    df.content = df.content.apply(lambda content: lower_case(content))

    return df

In [110]:
def normalize_sentence(sentence):
    sentence = lower_case(sentence)
    sentence = remove_stopwords(sentence)
    sentence = remove_num(sentence)
    sentence = remove_punctuatons(sentence)
    sentence = remove_urls(sentence)
    sentence = lemmatization(sentence)
    return sentence

In [113]:
normalize_sentence("that's it? it's done already? This is one")

"that's it done already one"

In [115]:
train_data.head()

                                                content  sentiment
6192  @BabyPatches I had a very good day - lots of s...          1
2150  @philritchie Boom, and if you will, boom! Saw ...          1
3118  @jaezors my b day is on may 13 but my party is...          1
8147  has just finished recording the improvisation ...          1
4949  I don't feel well. I feel like i could throw u...          0

In [116]:
train_data = normalize_text(train_data)
test_data = normalize_text(test_data)

In [117]:
train_data.head()

                                                content  sentiment
6192  babypatches i good day lot stretching sleeping...          1
2150  philritchie boom boom saw movie last night rea...          1
3118               jaezors b day may party sat come gay          1
8147  ha finished recording improvisation second ins...          1
4949  i feel well i feel like could throw throat hur...          0

# Feature Engineering

In [118]:
x_train = train_data['content'].values
x_test = test_data['content'].values

y_train = train_data['sentiment'].values
y_test = test_data['sentiment'].values

In [119]:
x_train.shape

(8299,)

In [120]:
x_test.shape

(2075,)

In [121]:
count_vectorizer = CountVectorizer()

x_train_bow = count_vectorizer.fit_transform(x_train)

x_test_bow = count_vectorizer.transform(x_test)

In [122]:
x_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 68435 stored elements and shape (8299, 14855)>

In [123]:
train_df = pd.DataFrame(x_train_bow.toarray())

train_df['label'] = y_train

In [124]:
train_df.head()

   0  1  2  3  4  5  6  ...  14849  14850  14851  14852  14853  14854  label
0  0  0  0  0  0  0  0  ...      0      0      0      0      0      0      1
1  0  0  0  0  0  0  0  ...      0      0      0      0      0      0      1
2  0  0  0  0  0  0  0  ...      0      0      0      0      0      0      1
3  0  0  0  0  0  0  0  ...      0      0      0      0      0      0      1
4  0  0  0  0  0  0  0  ...      0      0      0      0      0      0      0

[5 rows x 14856 columns]

# Model Building

In [131]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report

In [128]:
model = XGBClassifier(use_label_encoder=False)

In [129]:
model.fit(x_train_bow, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

# Model Evaluation

In [130]:
y_pred = model.predict(x_test_bow)

In [132]:
accuracy = accuracy_score(y_test, y_pred=y_pred)
classification_report = classification_report(y_test, y_pred)

In [133]:
print(f"Accuracy: {accuracy}")
print(f"\n\nclassification report: {classification_report}")

Accuracy: 0.7633734939759036


classification report:               precision    recall  f1-score   support

           0       0.73      0.82      0.77      1021
           1       0.80      0.71      0.75      1054

    accuracy                           0.76      2075
   macro avg       0.77      0.76      0.76      2075
weighted avg       0.77      0.76      0.76      2075